  import 'package:admin/screens/factory_layout/employee.dart';

  List<Employee> employees = [
    Employee(
      id: 1,
      name: '王宁',
      photo: 'assets/images/t1.jpg',
      workStationId: 1,
      workType: '早班',
    ),
    Employee(
      id: 2,
      name: '张磊',
      photo: 'assets/images/t2.jpg',
      workStationId: 4,
      workType: '晚班',
    ),
    Employee(
      id: 3,
      name: '陈婷',
      photo: 'assets/images/t3.jpg',
      workStationId: 3,
      workType: '夜班',
    ),
    Employee(
      id: 4,
      name: '刘阳',
      photo: 'assets/images/t4.jpg',
      workStationId: 2,
      workType: '早班',
    ),
    Employee(
      id: 5,
      name: '林晨',
      photo: 'assets/images/t5.jpg',
      workStationId: 5,
      workType: '晚班',
    ),
    Employee(
      id: 6,
      name: '黄芳',
      photo: 'assets/images/t6.jpg',
      workStationId: 1,
      workType: '晚班',
    ),
    Employee(
      id: 7,
      name: '吴勇',
      photo: 'assets/images/t7.jpg',
      workStationId: 3,
      workType: '夜班',
    ),
    Employee(
      id: 8,
      name: '徐秀英',
      photo: 'assets/images/t8.jpg',
      workStationId: 5,
      workType: '早班',
    ),
    Employee(
      id: 9,
      name: '李明',
      photo: 'assets/images/t9.jpg',
      workStationId: 2,
      workType: '夜班',
    ),
    Employee(
      id: 10,
      name: '周涛',
      photo: 'assets/images/t10.jpg',
      workStationId: 4,
      workType: '早班',
    ),
    Employee(
      id: 11,
      name: '许娟',
      photo: 'assets/images/t11.jpg',
      workStationId: 1,
      workType: '夜班',
    ),
    Employee(
      id: 12,
      name: '赵伟',
      photo: 'assets/images/t12.jpg',
      workStationId: 3,
      workType: '早班',
    ),
    Employee(
      id: 13,
      name: '马丽',
      photo: 'assets/images/t13.jpg',
      workStationId: 2,
      workType: '晚班',
    ),
    Employee(
      id: 14,
      name: '朱军',
      photo: 'assets/images/t14.jpg',
      workStationId: 5,
      workType: '夜班',
    ),
    Employee(
      id: 15,
      name: '何洋',
      photo: 'assets/images/t15.jpg',
      workStationId: 4,
      workType: '晚班',
    ),
    Employee(
      id: 16,
      name: '郑敏',
      photo: 'assets/images/t16.jpg',
      workStationId: 1,
      workType: '早班',
    ),
    Employee(
      id: 17,
      name: '孙强',
      photo: 'assets/images/t17.jpg',
      workStationId: 3,
      workType: '晚班',
    ),
    Employee(
      id: 18,
      name: '曹静',
      photo: 'assets/images/t18.jpg',
      workStationId: 2,
      workType: '夜班',
    ),
    Employee(
      id: 19,
      name: '蒋勇',
      photo: 'assets/images/t19.jpg',
      workStationId: 5,
      workType: '早班',
    ),
    Employee(
      id: 20,
      name: '丁娟',
      photo: 'assets/images/t20.jpg',
      workStationId: 4,
      workType: '夜班',
    ),
  ];

 List<Employee> employees2 = [
    Employee(
      id: 1,
      name: '王宁',
      photo: 'assets/images/t1.jpg',
      workStationId: 3,
      workType: '夜班',
    ),
    Employee(
      id: 2,
      name: '张磊',
      photo: 'assets/images/t2.jpg',
      workStationId: 1,
      workType: '夜班',
    ),
    Employee(
      id: 3,
      name: '陈婷',
      photo: 'assets/images/t3.jpg',
      workStationId: 5,
      workType: '早班',
    ),
    Employee(
      id: 4,
      name: '刘阳',
      photo: 'assets/images/t4.jpg',
      workStationId: 4,
      workType: '夜班',
    ),
    Employee(
      id: 5,
      name: '林晨',
      photo: 'assets/images/t5.jpg',
      workStationId: 2,
      workType: '早班',
    ),
    Employee(
      id: 6,
      name: '黄芳',
      photo: 'assets/images/t6.jpg',
      workStationId: 4,
      workType: '晚班',
    ),
    Employee(
      id: 7,
      name: '吴勇',
      photo: 'assets/images/t7.jpg',
      workStationId: 3,
      workType: '早班',
    ),
    Employee(
      id: 8,
      name: '徐秀英',
      photo: 'assets/images/t8.jpg',
      workStationId: 2,
      workType: '晚班',
    ),
    Employee(
      id: 9,
      name: '李明',
      photo: 'assets/images/t9.jpg',
      workStationId: 5,
      workType: '夜班',
    ),
    Employee(
      id: 10,
      name: '周涛',
      photo: 'assets/images/t10.jpg',
      workStationId: 1,
      workType: '晚班',
    ),
    Employee(
      id: 11,
      name: '许娟',
      photo: 'assets/images/t11.jpg',
      workStationId: 2,
      workType: '夜班',
    ),
    Employee(
      id: 12,
      name: '赵伟',
      photo: 'assets/images/t12.jpg',
      workStationId: 3,
      workType: '晚班',
    ),
    Employee(
      id: 13,
      name: '马丽',
      photo: 'assets/images/t13.jpg',
      workStationId: 5,
      workType: '夜班',
    ),
    Employee(
      id: 14,
      name: '朱军',
      photo: 'assets/images/t14.jpg',
      workStationId: 4,
      workType: '早班',
    ),
    Employee(
      id: 15,
      name: '何洋',
      photo: 'assets/images/t15.jpg',
      workStationId: 1,
      workType: '早班',
    ),
    Employee(
      id: 16,
      name: '郑敏',
      photo: 'assets/images/t16.jpg',
      workStationId: 2,
      workType: '夜班',
    ),
    Employee(
      id: 17,
      name: '孙强',
      photo: 'assets/images/t17.jpg',
      workStationId: 4,
      workType: '早班',
    ),
    Employee(
      id: 18,
      name: '曹静',
      photo: 'assets/images/t18.jpg',
      workStationId: 3,
      workType: '夜班',
    ),
    Employee(
      id: 19,
      name: '蒋勇',
      photo: 'assets/images/t19.jpg',
      workStationId: 1,
      workType: '早班',
    ),
    Employee(
      id: 20,
      name: '丁娟',
      photo: 'assets/images/t20.jpg',
      workStationId: 5,
      workType: '晚班',
    ),
];