import 'package:admin/screens/modify_check_in/employee.dart';

List<Employee> employees = [
  Employee(
    id: 1,
    name: '王宁',
    photo: 'assets/images/t1.jpg',
    position: '软件工程师',
    department: '技术部',
    todaySignInstate: '签到',
    todaySignOutstate: '未签退',
    lastSignIn: 4,
    lastLate: 3,
    lastSignOut: 3,
    lastLeaveEarly: 4,
  ),
  Employee(
    id: 2,
    name: '张磊',
    photo: 'assets/images/t2.jpg',
    position: '系统工程师',
    department: '技术部',
    todaySignInstate: '迟到',
    todaySignOutstate: '早退',
    lastSignIn: 2,
    lastLate: 5,
    lastSignOut: 5,
    lastLeaveEarly: 2,
  ),
  Employee(
    id: 3,
    name: '陈婷',
    photo: 'assets/images/t3.jpg',
    position: '产品经理',
    department: '产品部',
    todaySignInstate: '未签到',
    todaySignOutstate: '未签退',
    lastSignIn: 1,
    lastLate: 6,
    lastSignOut: 2,
    lastLeaveEarly: 5,
  ),
  Employee(
    id: 4,
    name: '刘阳',
    photo: 'assets/images/t4.jpg',
    position: '项目经理',
    department: '项目部',
    todaySignInstate: '签到',
    todaySignOutstate: '未签退',
    lastSignIn: 5,
    lastLate: 2,
    lastSignOut: 4,
    lastLeaveEarly: 3,
  ),
  Employee(
    id: 5,
    name: '李明',
    photo: 'assets/images/t5.jpg',
    position: '工程师',
    department: '策划部',
    todaySignInstate: '签到',
    todaySignOutstate: '未签退',
    lastSignIn: 6,
    lastLate: 1,
    lastSignOut: 7,
    lastLeaveEarly: 0,
  ),
  Employee(
    id: 6,
    name: '黄芳',
    photo: 'assets/images/t6.jpg',
    position: '销售经理',
    department: '销售部',
    todaySignInstate: '未签到',
    todaySignOutstate: '未签退',
    lastSignIn: 3,
    lastLate: 4,
    lastSignOut: 1,
    lastLeaveEarly: 6,
  ),
  Employee(
    id: 7,
    name: '吴勇',
    photo: 'assets/images/t7.jpg',
    position: '财务经理',
    department: '财务部',
    todaySignInstate: '迟到',
    todaySignOutstate: '早退',
    lastSignIn: 2,
    lastLate: 3,
    lastSignOut: 5,
    lastLeaveEarly: 2,
  ),
  Employee(
    id: 8,
    name: '徐秀英',
    photo: 'assets/images/t8.jpg',
    position: '人力资源经理',
    department: '人力资源部',
    todaySignInstate: '签到',
    todaySignOutstate: '未签退',
    lastSignIn: 7,
    lastLate: 0,
    lastSignOut: 3,
    lastLeaveEarly: 4,
  ),
  Employee(
    id: 9,
    name: '李明',
    photo: 'assets/images/t9.jpg',
    position: '工程师',
    department: '研发部',
    todaySignInstate: '未签到',
    todaySignOutstate: '未签退',
    lastSignIn: 2,
    lastLate: 5,
    lastSignOut: 1,
    lastLeaveEarly: 6,
  ),
  Employee(
    id: 10,
    name: '周涛',
    photo: 'assets/images/t10.jpg',
    position: '客户服务经理',
    department: '客户服务部',
    todaySignInstate: '签到',
    todaySignOutstate: '未签退',
    lastSignIn: 6,
    lastLate: 1,
    lastSignOut: 4,
    lastLeaveEarly: 3,
  ),
  Employee(
    id: 11,
    name: '许娟',
    photo: 'assets/images/t11.jpg',
    position: '测试工程师',
    department: '测试部',
    todaySignInstate: '未签到',
    todaySignOutstate: '未签退',
    lastSignIn: 3,
    lastLate: 4,
    lastSignOut: 2,
    lastLeaveEarly: 5,
  ),
  Employee(
    id: 12,
    name: '赵伟',
    photo: 'assets/images/t12.jpg',
    position: '技术支持工程师',
    department: '技术支持部',
    todaySignInstate: '迟到',
    todaySignOutstate: '未签退',
    lastSignIn: 4,
    lastLate: 3,
    lastSignOut: 3,
    lastLeaveEarly: 4,
  ),
  Employee(
    id: 13,
    name: '马丽',
    photo: 'assets/images/t13.jpg',
    position: '市场营销经理',
    department: '市场部',
    todaySignInstate: '签到',
    todaySignOutstate: '未签退',
    lastSignIn: 5,
    lastLate: 2,
    lastSignOut: 4,
    lastLeaveEarly: 3,
  ),
  Employee(
    id: 14,
    name: '朱军',
    photo: 'assets/images/t14.jpg',
    position: '质量控制经理',
    department: '质量控制部',
    todaySignInstate: '签到',
    todaySignOutstate: '未签退',
    lastSignIn: 6,
    lastLate: 1,
    lastSignOut: 4,
    lastLeaveEarly: 3,
  ),
  Employee(
    id: 15,
    name: '何洋',
    photo: 'assets/images/t15.jpg',
    position: '项目助理',
    department: '项目部',
    todaySignInstate: '迟到',
    todaySignOutstate: '未签退',
    lastSignIn: 7,
    lastLate: 0,
    lastSignOut: 3,
    lastLeaveEarly: 4,
  ),
  Employee(
    id: 16,
    name: '郑敏',
    photo: 'assets/images/t16.jpg',
    position: '运营经理',
    department: '运营部',
    todaySignInstate: '未签到',
    todaySignOutstate: '未签退',
    lastSignIn: 4,
    lastLate: 3,
    lastSignOut: 3,
    lastLeaveEarly: 4,
  ),
  Employee(
    id: 17,
    name: '孙强',
    photo: 'assets/images/t17.jpg',
    position: '物流经理',
    department: '物流部',
    todaySignInstate: '签到',
    todaySignOutstate: '未签退',
    lastSignIn: 5,
    lastLate: 2,
    lastSignOut: 4,
    lastLeaveEarly: 3,
  ),
  Employee(
    id: 18,
    name: '曹静',
    photo: 'assets/images/t18.jpg',
    position: '采购经理',
    department: '采购部',
    todaySignInstate: '签到',
    todaySignOutstate: '未签退',
    lastSignIn: 6,
    lastLate: 1,
    lastSignOut: 4,
    lastLeaveEarly: 3,
  ),
  Employee(
    id: 19,
    name: '蒋勇',
    photo: 'assets/images/t19.jpg',
    position: '客户关系经理',
    department: '客户关系部',
    todaySignInstate: '签到',
    todaySignOutstate: '未签退',
    lastSignIn: 7,
    lastLate: 0,
    lastSignOut: 3,
    lastLeaveEarly: 4,
  ),
  Employee(
    id: 20,
    name: '丁娟',
    photo: 'assets/images/t20.jpg',
    position: '安全监察员',
    department: '安全部',
    todaySignInstate: '未签到',
    todaySignOutstate: '未签退',
    lastSignIn: 4,
    lastLate: 3,
    lastSignOut: 3,
    lastLeaveEarly: 4,
  ),
];


  // Special Employee object for representing "not found" state
  Employee notFoundEmployee = Employee(
    id: -1,
    name: 'Not Found',
    photo: '',
    position: '工程师',
    department: '策划部',
    todaySignInstate: '签到',
    todaySignOutstate: '未签退',
    lastSignIn: 6,
    lastLate: 1,
    lastSignOut: 7,
    lastLeaveEarly: 0,
  );

    Employee tempEmployee = Employee(
    id: 7,
    name: '吴勇',
    photo: 'assets/images/t7.jpg',
    position: '财务经理',
    department: '财务部',
    todaySignInstate: '签到',
    todaySignOutstate: '早退',
    lastSignIn: 2,
    lastLate: 3,
    lastSignOut: 5,
    lastLeaveEarly: 2,
  );
